---
- name: Apply Kubernetes Deployment
  hosts: target_host
  become: yes
  gather_facts: yes

  tasks:
    
    - name: creating namespace argocd
      command: snap install kubectl
      become: yes

    - name: creating namespace argocd
      command: kubectl create namespace argocd
      become: yes

    - name: installing argo cd
      command: kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      become: yes

    - name: Port forward Argo CD to localhost
      command: kubectl port-forward svc/argocd-server -n argocd 8080:8080 &
      async: 0
      poll: 0
