---
- name: Install pre-requisite softwares on target
  hosts: target_host
  become: true
  tasks:
    - name: Install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Install Minikube
      command: >
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64 && chmod +x minikube && sudo mv minikube /usr/local/bin/
      args:
        creates: /usr/local/bin/minikube

    - name: Install Python 3.11
      apt:
        name: python3.11
        state: present

    - name: Install pip for Python 3.11
      apt:
        name: python3-pip
        state: present

    - name: Upgrade pip
      pip:
        executable: pip3.11
        name: pip
        state: latest

    - name: Install Docker Compose
      pip:
        executable: pip3.10
        name: docker-compose
        state: latest
